# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Categories
Category.create(name: 'Electronics')
Category.create(name: 'Home & Furniture')
Category.create(name: 'Outdoors')
Category.create(name: 'Toys')
Category.create(name: 'Books & Films')
Category.create(name: 'Services')

# Sub-categories
SubCategory.create(name: 'Headphones', category_id:1)
SubCategory.create(name: 'Laptops', category_id:1)
SubCategory.create(name: 'Cameras', category_id:1)
SubCategory.create(name: 'TVs', category_id:1)
SubCategory.create(name: 'Speakers',category_id:1)
SubCategory.create(name: 'Mobile Phone',category_id:1)
SubCategory.create(name: 'Tablets',category_id:1)
SubCategory.create(name: 'Tent',category_id:3)

# Tree logic
q1 = Question.create(content: "What style of headphone do you prefer?")

a1 = Answer.create(content: 'In-ear', question: q1)
a2 = Answer.create(content: 'Over-ear', question: q1)

q2 = Question.create(content: 'Will you be using your headphones to talk on the phone?', parent_answer: a1)
q3 = Question.create(content: 'Will you be using your headphones to talk on the phone?', parent_answer: a2)

a3 = Answer.create(content: 'Yes', question: q2)
a4 = Answer.create(content: 'No', question: q2)
a5 = Answer.create(content: 'Yes', question: q3)
a6 = Answer.create(content: 'No', question: q3)

q4 = Question.create(content: 'Where will you primarily be using your headphones?', parent_answer: a3)
q5 = Question.create(content: 'Where will you primarily be using your headphones?', parent_answer: a4)
q6 = Question.create(content: 'Where will you primarily be using your headphones?', parent_answer: a5)
q7 = Question.create(content: 'Where will you primarily be using your headphones?', parent_answer: a6)

a7 = Answer.create(content: 'At home', question: q4)
a8 = Answer.create(content: 'At work', question: q4)
a9 = Answer.create(content: 'On the go', question: q4)
a10 = Answer.create(content: 'Everywhere', question: q4)
a11 = Answer.create(content: 'At home', question: q5)
a12 = Answer.create(content: 'At work', question: q5)
a13 = Answer.create(content: 'On the go', question: q5)
a14 = Answer.create(content: 'Everywhere', question: q5)
a15 = Answer.create(content: 'At home', question: q6)
a16 = Answer.create(content: 'At work', question: q6)
a17 = Answer.create(content: 'On the go', question: q6)
a18 = Answer.create(content: 'Everywhere', question: q6)
a19 = Answer.create(content: 'At home', question: q7)
a20 = Answer.create(content: 'At work', question: q7)
a21 = Answer.create(content: 'On the go', question: q7)
a22 = Answer.create(content: 'Everywhere', question: q7)

q8 = Question.create(content: 'Do you care about noise cancellation features?', parent_answer: a7)
q9 = Question.create(content: 'Do you care about noise cancellation features?', parent_answer: a8)
q10 = Question.create(content: 'Will you be exercising with your headphones on?', parent_answer: a9)
q11 = Question.create(content: 'Will you be exercising with your headphones on?', parent_answer: a10)
q12 = Question.create(content: 'Do you care about noise cancellation features?', parent_answer: a11)
q13 = Question.create(content: 'Do you care about noise cancellation features?', parent_answer: a12)
q14 = Question.create(content: 'Will you be exercising with your headphones on?', parent_answer: a13)
q15 = Question.create(content: 'Will you be exercising with your headphones on?', parent_answer: a14)
q16 = Question.create(content: 'Do you care about noise cancellation features?', parent_answer: a15)
q17 = Question.create(content: 'Do you care about noise cancellation features?', parent_answer: a16)
q18 = Question.create(content: 'Will you be exercising with your headphones on?', parent_answer: a17)
q19 = Question.create(content: 'Will you be exercising with your headphones on?', parent_answer: a18)
q20 = Question.create(content: 'Do you care about noise cancellation features?', parent_answer: a19)
q21 = Question.create(content: 'Do you care about noise cancellation features?', parent_answer: a20)
q22 = Question.create(content: 'Will you be exercising with your headphones on?', parent_answer: a21)
q23 = Question.create(content: 'Will you be exercising with your headphones on?', parent_answer: a22)

a23 = Answer.create(content: "Yes", question: q8)
a24 = Answer.create(content: "No", question: q8)
a25 = Answer.create(content: "Yes", question: q9)
a26 = Answer.create(content: "No", question: q9)
a27 = Answer.create(content: "Yes", question: q10)
a28 = Answer.create(content: "No", question: q10)
a29 = Answer.create(content: "Yes", question: q11)
a30 = Answer.create(content: "No", question: q11)
a31 = Answer.create(content: "Yes", question: q12)
a32 = Answer.create(content: "No", question: q12)
a33 = Answer.create(content: "Yes", question: q13)
a34 = Answer.create(content: "No", question: q13)
a35 = Answer.create(content: "Yes", question: q14)
a36 = Answer.create(content: "No", question: q14)
a37 = Answer.create(content: "Yes", question: q15)
a38 = Answer.create(content: "No", question: q15)
a39 = Answer.create(content: "Yes", question: q16)
a40 = Answer.create(content: "No", question: q16)
a41 = Answer.create(content: "Yes", question: q17)
a42 = Answer.create(content: "No", question: q17)
a41 = Answer.create(content: "Yes", question: q18)
a42 = Answer.create(content: "No", question: q18)
a41 = Answer.create(content: "Yes", question: q19)
a42 = Answer.create(content: "No", question: q19)
a41 = Answer.create(content: "Yes", question: q20)
a42 = Answer.create(content: "No", question: q20)
a41 = Answer.create(content: "Yes", question: q21)
a42 = Answer.create(content: "No", question: q21)
a41 = Answer.create(content: "Yes", question: q22)
a42 = Answer.create(content: "No", question: q22)
a41 = Answer.create(content: "Yes", question: q23)
a42 = Answer.create(content: "No", question: q23)

q24 = Question.create(content: "What's your budget?", parent_answer: a23)
q25 = Question.create(content: "What's your budget?", parent_answer: a24)
q26 = Question.create(content: "What's your budget?", parent_answer: a25)
q27 = Question.create(content: "What's your budget?", parent_answer: a26)
q28 = Question.create(content: "What's your budget?", parent_answer: a27)
q29 = Question.create(content: "What's your budget?", parent_answer: a28)
q31 = Question.create(content: "What's your budget?", parent_answer: a29)
q31 = Question.create(content: "What's your budget?", parent_answer: a30)
q32 = Question.create(content: "What's your budget?", parent_answer: a31)
q33 = Question.create(content: "What's your budget?", parent_answer: a32)
q34 = Question.create(content: "What's your budget?", parent_answer: a33)
q35 = Question.create(content: "What's your budget?", parent_answer: a34)
q36 = Question.create(content: "What's your budget?", parent_answer: a35)
q37 = Question.create(content: "What's your budget?", parent_answer: a36)
q38 = Question.create(content: "What's your budget?", parent_answer: a37)
q39 = Question.create(content: "What's your budget?", parent_answer: a38)
q40 = Question.create(content: "What's your budget?", parent_answer: a39)
q41 = Question.create(content: "What's your budget?", parent_answer: a40)
q42 = Question.create(content: "What's your budget?", parent_answer: a41)
q43 = Question.create(content: "What's your budget?", parent_answer: a42)
